version: "3.9"

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  db:
    image: postgresql:alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    # depends_on:
    #   - db
    # backend:
    #   build: ./backend
    #   depends_on:
    #     - db
    # frontend:
    #   build: ./frontend
    #   depends_on:
    #     - backend
