version: "3.9"

services:
    tunnel:
        image: cloudflare/cloudflared:latest
        command: tunnel run
        env_file: ./.env
        environment:
            - TUNNEL_TOKEN=${TUNNEL_TOKEN}

    db:
        image: postgres:alpine
        env_file: ./.env
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    redis:
        image: redis:alpine

    worker:
        build: ./backend
        command: rq worker low medium high
        depends_on:
            - backend
            - redis

    backend:
        build: ./backend
        command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind :8000
        depends_on:
            - db
            - worker

    frontend:
        build: ./frontend
        command: node .output/server/index.mjs
        depends_on:
            - backend
