version: "3.9"

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - db

  redis:
    image: redis/redis-stack:latest

  rq:
    image: python:3.11-alpine
    env_file: ./api/prod.env
    command: sh -c "pip install rq && rq worker-pool -u ${RQ_URL} -n 8"
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=redis-datasource

  api:
    build: ./api
    command: gunicorn main:app --workers 8 --worker-class uvicorn.workers.UvicornWorker --bind :8080
    environment:
      - ENVIRONEMENT=PROD
    depends_on:
      - db
      - rq

  frontend:
    build: ./frontend
    command: node .output/server/index.mjs
    depends_on:
      - api
