version: "3.9"

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    env_file: ./.env
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run

  db:
    image: postgres:alpine
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - db

  redis:
    image: redis/redis-stack:latest

  rq:
    image: python:3.11-alpine
    env_file: ./api/prod.env
    command: sh -c "pip install rq && rq worker-pool -u ${RQ_URL} -n 8"
    depends_on:
      - redis

  rq-dashboard:
    image: python:3.11-alpine
    env_file: ./api/prod.env
    command: sh -c "pip install rq-dashboard && rq-dashboard -u ${RQ_URL}"
    depends_on:
      - rq

  api:
    build: ./api
    command: gunicorn main:app --workers 8 --worker-class uvicorn.workers.UvicornWorker --bind :8000
    environment:
      - ENVIRONEMENT=PROD
    depends_on:
      - db
      - rq

  frontend:
    build: ./frontend
    command: node .output/server/index.mjs
    depends_on:
      - api
