version: "3.9"

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine

  rq:
    image: python:3.11-alpine
    env_file: ./backend/.env
    command: pip install rq && rq worker-pool -u ${RQ_URL} low medium high -n 8
    depends_on:
      - backend
      - redis

  rq-dashboard:
    image: python:3.11-alpine
    env_file: ./backend/.env
    command: pip install rq-dashboard && rq-dashboard -u ${RQ_URL}
    depends_on:
      - rq

  backend:
    build: ./backend
    command: gunicorn main:app --workers 8 --worker-class uvicorn.workers.UvicornWorker --bind :8000
    depends_on:
      - db
      - worker

  frontend:
    build: ./frontend
    command: node .output/server/index.mjs
    depends_on:
      - backend
