version: "3.9"

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

  posdbtgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - db
  
  redisinsight:
    image: redislabs/redisinsight:latest
    depends_on:
      - redis

  rq:
    image: python:3.11-alpine
    env_file: ./api/.env
    command: pip install rq && rq worker-pool -u ${RQ_URL} low medium high -n 8
    depends_on:
      - redis

  rqdashboard:
    image: python:3.11-alpine
    env_file: ./api/.env
    command: pip install rq-dashboard && rq-dashboard -u ${RQ_URL} -p 80
    depends_on:
      - rq

  api:
    build: ./api
    command: gunicorn main:app --workers 8 --worker-class uvicorn.workers.UvicornWorker --bind :8000
    depends_on:
      - db
      - rq

  frontend:
    build: ./frontend
    command: node .output/server/index.mjs
    depends_on:
      - api
