version: "3.9"

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

  database:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - database

  redis-stack:
    image: redis/redis-stack:latest

  rq:
    image: python:3.11-alpine
    env_file: ./api/.env
    command: pip install rq && rq worker-pool -u ${RQ_URL} low medium high -n 8
    depends_on:
      - redis-stack

  rqdashboard:
    image: python:3.11-alpine
    env_file: ./api/.env
    command: pip install rq-dashboard && rq-dashboard -u ${RQ_URL} -p 80
    depends_on:
      - rq

  api:
    build: ./api
    command: gunicorn main:app --workers 8 --worker-class uvicorn.workers.UvicornWorker --bind :8000
    depends_on:
      - database
      - rq

  frontend:
    build: ./frontend
    command: node .output/server/index.mjs
    depends_on:
      - api
