[tool.poetry]
name = "api"
version = "0.0.1"
description = ""
authors = ["Mehdi Rtal <mehdirtal7@pm.me>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.109.0"
sqlmodel = "^0.0.14"
gunicorn = "^21.2.0"
uvicorn = "^0.25.0"
asyncpg = "^0.29.0"
alembic = "^1.12.1"
fastapi-restful = "^0.5.0"
fastapi-cache2 = "^0.2.1"
redis = {extras = ["hiredis"], version = "^5.0.1"}
rq = "^1.15.1"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
sendgrid = "^6.10.0"
orjson = "^3.9.10"
email-validator = "^2.1.0.post1"
python-multipart = "^0.0.6"
python-dotenv = "^1.0.0"
typing-inspect = "^0.9.0"
pydantic-settings = "^2.1.0"
sellix-python-sdk = "^1.0.9.1"
sentry-sdk = "^1.39.2"
httpx-oauth = "^0.13.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
