name: Production CI

on:
    workflow_dispatch:

jobs:
    test-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache Docker images
              id: cache-docker
              uses: ScribeMD/docker-cache@0.3.7
              with:
                key: docker-${{ runner.os }}-${{ hashFiles('**/docker-compose.yml') }}

            - name: Set up Just
              uses: taiki-e/install-action@just

            - name: Build Docker images
              if: steps.cache-docker.outputs.cache-hit != 'true'
              run: just build

            - name: Run Docker containers
              run: just up

            # - name: Run tests
            #   run: just test
