name: Test

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Just
              uses: taiki-e/install-action@just

            - name: Docker compose up
              run: just up

            - name: Test
              run: just test
